### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by konstruktiv** [rochus-keller/CrossLine#1]
Hello, thanks for releasing CrossLine!

On Ubuntu, I ran your Windows build using Wine and it worked nicely. I then followed your build instructions, but trying to compile with Qt5. It was definitely not straightforward and I had to stop after a couple of hours and many errors.

Do you plan to publish adapted build instructions or otherwise support Linux?

**Comment by konstruktiv** [comment]
Thanks for the quick build! It works, all I had to do was install libpng12. 

Which Qt packages contain the private classes? That is a prerequisite for building that no longer seems to be available in the Ubuntu repos.

**Comment by rochus-keller** [comment]
Ok, great. 

>> Which Qt packages contain the private classes?
Have a look at the source code; you can search for "private/" using QtCreator; it gives me the following source files which use private Qt features: Indexer.cpp, OutlineTree.cpp, TextHtmlParser.cpp/h, TextView.cpp. E.g. qtreeview_p.h, qtextdocument_p.h and a couple of headers from tools/assistant/lib/fulltextsearch are used.

**Comment by rochus-keller** [comment]
There are "private-dev" packages available, e.g. qtbase5-private-dev. But don't forget that QTreeView::indexRowSizeHint has to be virtual for the outliner to work; it is mentioned in the preconditions section; if you do that change the Qt Widget module has to be re-built.
