### ISSUE TITLE
Feature request: grouping items within a level

### ISSUE THREAD

**Issue by th** [rochus-keller/CrossLine#10]
This is something no outliner I've ever seen does, and it drives me mad:

I'd like to have groupings (distinct from the indent hierarchy) for items. I'm usually either simulating it using "empty" parent items (which leads to an incorrect structure if all items are logically on the same level, and the empty items looks bad) or ignore the grouping and have distinct types of items on the same level without any differentiation.

Groupings could be visually indicated, but weakly, maybe a small gap, different background coloring or a thin small line around groups of items.

**Comment by rochus-keller** [comment]
That sounds like you are fighting against the concept of an outliner; if there are items belonging together, the whole purpose of an outliner is to unite them undere a common super item; if you have items logically belonging to more than one super item, you can make an alias and put that under different super items.

Can you make an example what you are using groupings for in practice?

**Comment by th** [comment]
I'll just shorten and translate a bit from some notes (a sociology class):

* classes
** antagonistic
** Bourgeoisie
*** lots more
** Proletariat
*** lots more

"Antagonistic" isn't a third class, obviously, but it feels very verbose to add an item "2 kinds of classes", just to get the structure right. If I could "bracket" Bourgeoisie and Proletariat somehow, the "antagonistic" wouldn't be so strange here.

**Comment by rochus-keller** [comment]
Then "classes" is likely the wrong title; Bourgeousie and Proletariat together constitute the "society", and "antagonistic" is a relation between them; you cannot represent that with a tree structure. But an outliner is not an ontology modeling tool anyway.
