### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by anthrolisp** [rochus-keller/CrossLine#3]
On Ubuntu 19.04.
QT4 installed
Downloaded, and extracted: CrossLine_linux_x86.tar.gz

```
$ ./CrossLine 
bash: ./CrossLine: No such file or directory
```

**Comment by rochus-keller** [comment]
Are you in the right directory? As it seems the file CrossLine is not there. Where did you unpack it? 
You don't actually need to install a separate Qt4 because it is statically linked in the executable.

**Comment by anthrolisp** [comment]
When I go to extract "CrossLine_linux_x86.tar.gz" it only fines one file "CrossLine", not a directory. Should I clone the entire project instead?

**Comment by rochus-keller** [comment]
No, that is the executable. Just make sure it is in the directory where you execute ./CrossLine in the bash shell and also make sure that the file has executable rights. Also remember that you might need additional libraries if you want to run an x86 executable on an x86-64 system (in case the latter applies to your system).

**Comment by rochus-keller** [comment]
Were you able to solve the problem?

**Comment by anthrolisp** [comment]
I got it working on the Windows computer at work. Just tried again on my Linux machine at home:

```
$ ./CrossLine 
./CrossLine: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
```

That library is showing installed:
`libpng12-0 is already the newest version (1.2.54-1ubuntu1).`

Thoughts?

**Comment by rochus-keller** [comment]
Try to call ldd CrossLine and see what libraries and versions are missing; maybe it's a 32/64 bit version issue. Actually the Windows version runs just fine on Linux with Wine.

**Comment by rochus-keller** [comment]
Another idea: if libpng12.so.0 is indeed missing in your file system you could create a symbolic link in the library directory pointing to the libpng.so version which is delivered with your linux and call it libpng12.so.0. But also here: the 32 bit version of the library is required.

**Comment by metastork** [comment]
Nice software Rochus! Some instructions and files are available here for making it work on newer Ubuntu systems, which don't ship with the older libpng12 version anymore: https://www.linuxuprising.com/2018/05/fix-libpng12-0-missing-in-ubuntu-1804.html

**Comment by rochus-keller** [comment]
Thanks. I suppose it should be enough to just create a symbolic link to the newer version and name it like the missing version.
