### ISSUE TITLE
Release x86_64 build for Windows with Lua enabled, misc.

### ISSUE THREAD

**Issue by savchenko** [rochus-keller/CrossLine#5]
Hi and thank you for releasing this as an open-source application. 
Would you consider publishing x86_64 with `lua` enabled?

Also, you mention Lucene in the readme, is there some more documentation on how CrossLine interfaces with it apart from comments available in the [Indexer.cpp](https://github.com/rochus-keller/CrossLine/blob/master/Indexer.cpp)?

Lastly, downloads point to `http://` while `https://` returns an invalid certificate (well, valid for *.kasserver.com, kasserver.com only)

Thanks again!

**Comment by rochus-keller** [comment]
Welcome. 
> Would you consider publishing x86_64 with lua enabled?

I'm only using the 32 bit version and never compiled/testet it on 64 bit. Likely some modifications are required to make it work. It's currently not on my agenda. Maybe someone else want's to have a look at it.

> is there some more documentation on how CrossLine interfaces with it

Previous versions of CrossLine used the C++ version of Lucene integrated with Qt. I replaced it with my own full text search engine (https://github.com/rochus-keller/Fts) to avoid dependence on the private Qt API. But you can still enable it with CONFIG += HasCLucene.

> downloads point to http:// 

Only the http links are supported. Https seems to work though if you accept the certificate of my provider.

**Comment by rochus-keller** [comment]
Meanwhile I migrated CrossLine away from Qt 4 to my LeanQt version (which corresponds to Qt 5). As a side effect I offer pre-compiled versions for Windows, Linux and Mac, including x86_64 for all three platforms.

The Lua and CLucene binding is not yet migrated. 

I will likely migrate the Lua binding, but not CLucene which is no longer required by CrossLine and not supported by LeanQt so far.

I close this for now; if you still need the Lua binding, pleas open a new issue.
