### ISSUE TITLE
Question about further support and contributions

### ISSUE THREAD

**Issue by ThGkasios** [rochus-keller/CrossLine#6]
Hello, I've been using CrossLine for a few months now, and it has helped me a great deal with notes. I would like to ask if you would accept code contributions for CrossLine; I've been trying to study the source code and would be happy to help further the development somewhat, or try and "unhinge" it from Qt, if that is desirable.

By the way, the archivum.com link seems to not lead anywhere anymore.

Edit: Also, I would like to mention that for a text processor, _the Shift+Arrow Keys should be used for selecting text_ in order to highlight it or manage it. It is the only thing I still stumble upon when I use CrossLine. (Many a time have rows risen too far left in the outliner, making it difficult to put everything back together).

**Comment by rochus-keller** [comment]
Thanks for your feedback; glad it was useful to you.

> ask if you would accept code contributions for CrossLine

Since I don't have much time for CrossLine and it does everything I need it might be a better idea if you fork it.

> and would be happy to help further the development somewhat

What features would you like to develop?

> or try and "unhinge" it from Qt

That would rather be a complete rewrite because the code heavily depends on Qt. What benefit do you see when "unhinging" it from Qt?

> archivum.com link seems to not lead anywhere anymore.

Where did you see that link?

**Comment by ThGkasios** [comment]
Thanks for responding!

> ...it might be a better idea if you fork it.

Alrighty!

> What features would you like to develop?

I was introduced to outliners by another person using Ecco Pro, who had wanted to find something as an alternative, in case Ecco Pro became for some reason unusable on a future Windows version. My first shots would be implementing

- coloured fonts, and
- a small amount of GUI on the top that executes the already implemented functions,

but above all else,

- I would make **shift+arrowkeys** select text instead of shifting a row left and right. _(The same is already - and quite intuitively - done with **Tab** and **Shift+Tab**.)_ It's a knitpick, but after this time it still takes me effort to not pick a line and drive it from level 5 all the way left , dragging up anything under it.

>  What benefit do you see when "unhinging" it from Qt?

I haven't used Qt so far, and it looks like it has a somewhat steep learning curve as an application, so I would rather implement elements by code instead of changing platforms, and there is enough base code to support guiding a rewrite.

>>archivum.com link seems to not lead anywhere anymore.
>
>Where did you see that link?

It is in _How to Build CrossLine >> Preconditions >> If you intend to do static builds on Windows..._, on the _README.md_

**Comment by rochus-keller** [comment]
> it has a somewhat steep learning curve as an application, so I would rather implement elements by code instead of changing platforms

Don't understand what you mean. Every widget is rendered within Qt and you have all the source code. I don't think there is a framework that is as powerful and performant as Qt, and that has remained so stable for so many years and so easy to get speed on. What people accuse Qt of, namely that a very moderate C++ style is used, and not policy-based design, I consider rather an advantage.

> It is in How to Build CrossLine >> Preconditions >> If you intend to do static builds on Windows

I'll take a look at it. Actually what is important in the refereced article is explicitly stated under "Here is the summary on how to do implement Qt Win32 static builds:".

**Comment by ThGkasios** [comment]
Oh, I thought Qt was an IDE itself. I haven't used it so far, and all C++ projects I've done where 350max-line things from scratch, so I haven't formed an opinion, but having worked with tensorflow, I understand that when versions of applications have conflicts, it usually means trouble (a.k.a. a very steep learning curve). I'll look into it!
