### ISSUE TITLE
Add example project file

### ISSUE THREAD

**Issue by savchenko** [rochus-keller/CrossLine#8]
This image shows many non-obvious features:

![img](https://camo.githubusercontent.com/0c58df422a80092b328de323210930665ebda92c60adf99ede39aad61094c5fa/687474703a2f2f736f6674776172652e726f636875732d6b656c6c65722e63682f63726f73736c696e6564656d6f73637265656e73686f742e706e67)

Can it be added in lieu of documentation?

**Comment by rochus-keller** [comment]
Not sure if I understand what you mean. The given image is actually a screenshot of CrossLine with the demo repository (http://software.rochus-keller.ch/CrossLineDemo.cldb). Unfortunately there is nothing like a "documentation" yet, but the demo repository includes a lot of hints about what CrossLine can do and how to operate it.

**Comment by rochus-keller** [comment]
Ok, I should do so.

**Comment by rochus-keller** [comment]
done.
